name: Deploy Docker App on Self-Hosted Runner

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t myapp:latest . 

    - name: Stop and remove old container (if exists)
      run: |
        docker stop myapp || true
        docker rm myapp || true

    - name: Run new container
      run: |
        docker run -d --name myapp -p 80:80 myapp:latest
